name = "cms-calculator-api"
main = "src/workers/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "cms-calculator-db"
database_id = "your-database-id"

# KV Namespace for caching
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-id"
preview_id = "your-kv-preview-id"

# R2 Bucket for file storage
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "cms-calculator-storage"

# Queue for background jobs
[[queues.producers]]
binding = "QUEUE"
queue = "cms-calculator-queue"

[[queues.consumers]]
queue = "cms-calculator-queue"
max_batch_size = 10
max_batch_timeout = 30

# Cron Triggers for scheduled jobs
[triggers.crons]
# 사이트맵 갱신 (6시간마다)
sitemap_refresh = "0 */6 * * *"
# 색인 제출 (매일 오전 2시)
index_submission = "0 2 * * *"
# 분석 데이터 집계 (매일 오전 3시)
analytics_aggregation = "0 3 * * *"
# 깨진 링크 스캔 (매주 월요일 오전 4시)
broken_link_scan = "0 4 * * 1"
# 콘텐츠 리프레시 큐 처리 (30분마다)
content_refresh_queue = "*/30 * * * *"

# Environment variables
[vars]
JWT_SECRET = "your-jwt-secret"
INDEXNOW_KEY = "your-indexnow-key"
EMAIL_API_URL = "https://api.sendgrid.com/v3/mail/send"
EMAIL_API_KEY = "your-email-api-key"
WEBHOOK_SECRET = "your-webhook-secret"
GSC_CLIENT_EMAIL = "your-service-account-email"
GSC_PRIVATE_KEY = "your-private-key"

# CORS settings for API (Production에서는 더 엄격하게 설정)
[cors]
allowed_origins = ["http://localhost:3000", "https://your-domain.com"]
allow_credentials = true
allow_headers = ["Authorization", "Content-Type", "X-Requested-With"]
allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS", "HEAD"]
max_age = 86400

# 보안 헤더 (추가 권장)
[build.upload]
format = "modules"

# Rate limiting (추가 권장)
# 현재 Wrangler에서는 직접 지원하지 않으므로 코드에서 구현
