# Staging 환경 설정
name = "cms-calculator-api-staging"
main = "src/workers/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Staging D1 Database
[[d1_databases]]
binding = "DB"
database_name = "cms-calculator-staging"
database_id = "your-staging-database-id"

# Staging KV Namespace
[[kv_namespaces]]
binding = "CACHE"
id = "your-staging-kv-id"

# Staging R2 Bucket
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "cms-calculator-staging-storage"

# Staging Queue
[[queues.producers]]
binding = "QUEUE"
queue = "cms-calculator-staging-queue"

[[queues.consumers]]
queue = "cms-calculator-staging-queue"
max_batch_size = 5  # Staging에서는 더 작은 배치
max_batch_timeout = 30

# Staging Cron Triggers (더 빈번한 실행으로 테스트)
[triggers.crons]
sitemap_refresh = "*/30 * * * *"  # 30분마다
index_submission = "0 */2 * * *"  # 2시간마다
analytics_aggregation = "*/15 * * * *"  # 15분마다
broken_link_scan = "0 */4 * * *"  # 4시간마다
content_refresh_queue = "*/10 * * * *"  # 10분마다

# Staging Environment variables
[vars]
JWT_SECRET = "your-staging-jwt-secret"
INDEXNOW_KEY = "your-staging-indexnow-key"
EMAIL_API_URL = "https://api.sendgrid.com/v3/mail/send"
EMAIL_API_KEY = "your-staging-email-api-key"
WEBHOOK_SECRET = "your-staging-webhook-secret"
GSC_CLIENT_EMAIL = "your-staging-service-account@project.iam.gserviceaccount.com"
GSC_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\nyour-staging-private-key\n-----END PRIVATE KEY-----"

# Staging CORS
[cors]
allowed_origins = ["https://staging.your-domain.com", "http://localhost:3000"]
allow_credentials = true
allow_headers = ["Authorization", "Content-Type", "X-Requested-With"]
allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS", "HEAD"]
max_age = 86400

[build.upload]
format = "modules"
